In comments, fix typos.
nlsandler/writing-a-c-compiler-tests pull request #87
Opened 2024-10-18 04:37 UTC by ysono

This PR modifies intra-sample comments only.

One thing I left untouched: in `tests/chapter_10/valid/libraries/external_linkage_function_client.c`, `add_three_and_four()`, comment says the `sum()` function is shadowed, but it's not.

2024-10-21 21:37 UTC, nlsandler commented
Thank you for this PR! LGTM except one nit about "eightbytes". I also flagged a couple pre-existing typos that it makes sense to fix in this PR. I'll run the workflows once you've made those chances (or let me know if you'd prefer I make them myself).

Thanks for the catch about the comment in `tests/chapter_10/valid/libraries/external_linkage_function_client.c` - I'll open a separate PR for that.

2024-10-28 21:32 UTC, nlsandler requested changes
Looks good, just needs a few tiny tweaks - let me know whether you'd rather make those fixes or just have me do it.

2024-10-29 07:09 UTC, ysono commented
Thanks for your corrections. Please go ahead and make the adjustments.

2024-10-29 20:51 UTC, nlsandler approved these changes

2024-10-30 21:11 UTC, merged