Improve test samples to catch more errors.
nlsandler/writing-a-c-compiler-tests pull request #88
Opened 2024-10-18 04:39 UTC by ysono

This PR changes some samples to correctly catch some errors as intended.

I edited `expected_results.json` manually, without running `generate_expected_results.py`. Should we enable the Github Actions on non-`main` branches too?

One thing I left untouched: `tests/chapter_6/valid/ternary_rh_binop.c`: this test passes on solutions that prioritize either the logic or the conditional operator. Maybe using something other than `||` operator on the RHS would be better?

2024-10-21 22:30 UTC, nlsandler commented
This is great, thank you! `.github/workflows/check_autogen_files.yml` will run for this PR, but it should pass - the change you made to `expected_results.json` looks identical to what the script would have changed.

Thanks for flagging the issue in `ternary_rh_binop.c` - I'll open a separate PR to fix that.

2024-10-28 21:30 UTC, nlsandler requested changes
Looks good overall - just one question and one spot where we need to update a comment to match your change

2024-10-29 07:23 UTC, ysono commented
As with the other PR, please feel free to make amendments. I think you have far better context for how the final change should look like.

2024-10-29 18:54 UTC, nlsandler commented on tests/chapter_11/valid/implicit_casts/common_type.c
> +     * the result would be -2147483647 / 10, or -214748364.
Ah, you're absolutely right and I made a stupid arithmetic mistake. Thank you!

2024-10-29 19:00 UTC, nlsandler approved these changes

2024-10-30 22:44 UTC, merged